"""Rescore result files from raw metrics (trade ratio + fixed grade) without
touching them: writes results/rescored/<file>.jsonl (per-row verdicts) and
results/rescored/<file>.md (summary tables), plus an index in
results/rescored/README.md.

  python3 tools/rescore.py                       # every results/*.jsonl
  python3 tools/rescore.py results/theme.jsonl --colonist-enemies 4
"""
import argparse
import json
from pathlib import Path

import _path  # noqa: F401
from rca import ROOT
from rca.eval import report, scoring
from rca.eval.harness import load_manifests
from rca.eval.results import read_rows

SKIP = ("errors", "hazards")       # not episode rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="*", type=Path)
    ap.add_argument("--colonist-enemies", type=float, default=scoring.COLONIST_ENEMIES)
    ap.add_argument("--out", type=Path, default=ROOT / "results/rescored")
    a = ap.parse_args()
    files = a.files or sorted(p for p in (ROOT / "results").glob("*.jsonl")
                              if not any(s in p.name for s in SKIP))
    mean = {m["id"]: scoring.manifest_mean_points(m) for m in load_manifests(
        [p.stem.removeprefix("scenario_") for p in sorted((ROOT / "scenarios_out").glob("*.json"))])}
    a.out.mkdir(parents=True, exist_ok=True)
    index = ["# Rescored results", "",
             f"Generated by `tools/rescore.py` (colonist = {a.colonist_enemies:g} enemies by points). "
             "Raw files in results/ are untouched; see EVAL_SPEC.md §5-§7.", ""]
    for f in files:
        rows = [r for r in read_rows(f) if "scenario" in r]
        if not rows:
            continue
        with (a.out / f.name).open("w") as out:
            for r in rows:
                e = report.enrich(r, mean.get(r["scenario"]), a.colonist_enemies)
                t = e["trade"]
                out.write(json.dumps({
                    "scenario": r["scenario"], "agent": r["agent"], "agent_raw": r["agent_raw"],
                    "agent_version": r.get("agent_version"), "time": r.get("time"),
                    "cycle": r.get("cycle"), "reflex": r.get("reflex"),
                    "reflex_version": r.get("reflex_version"),
                    "grade_stored": r.get("grade"), "grade_v1": e["grade_v1"], "grade": e["grade"],
                    "deaths": r["deaths"], "score_v1": e["score_v1"],
                    "enemy_lost_points": t["enemy_lost_points"], "our_lost_points": t["our_lost_points"],
                    "ler": scoring.json_ler(t["ler"]), "ler_basis": t["ler_basis"]}) + "\n")
        s = report.summarize(rows, mean, colonist_enemies=a.colonist_enemies)
        (a.out / f.with_suffix(".md").name).write_text(report.render(s, f.name) + "\n")
        changed = sum(report.enrich(r, None)["grade"] != report.enrich(r, None)["grade_v1"]
                      for r in rows)
        index.append(f"- [{f.stem}]({f.stem}.md): {len(rows)} rows, {len(s)} config(s); "
                     f"grade changed by the decisive fix in {changed} rows")
        print(f"{f.name}: {len(rows)} rows -> {a.out / f.name}")
    (a.out / "README.md").write_text("\n".join(index) + "\n")


if __name__ == "__main__":
    main()
